spring:
  application:
    name: spring-ai-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:30b
    openai:
    #  add key
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.9
      embedding:
        options:
          model: text-embedding-3-small

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: chat_memory

    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:

    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        show-sql: true

  logging:
    level:
      org.springframework.ai:
        chat.client: DEBUG

server:
  port: 8081